name: unphar
main: DaisukeDaisuke\unphar\Main
version: 3.0.3
api:
- 3.22.0
commands:
  unphar:
    description: "Please use from console"
    usage: "/unphar"
    permission: "DaisukeDaisuke.unphar.use"
permissions:
  DaisukeDaisuke.unphar.use:
    default: op
