name: unphar
main: DaisukeDaisuke\unphar\unphar
version: 3.0.1
api:
- 1.0.0
- 2.0.0
- 3.0.0
- 4.0.0
commands:
  unphar:
    description: "Please use from console"
    usage: "/unphar"
    permission: "DaisukeDaisuke.unphar.use"
permissions:
  DaisukeDaisuke.unphar.use:
    default: op # can also be false, or op
